version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: POS_USER
      POSTGRES_PASSWORD: POS_PASSWORD
      POSTGRES_DB: POS_DB
    ports:
      - "5050:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
